name: Show Time App

on:
  push:
    branches: [ "workflow" ]
  pull_request:
    branches: [ "workflow" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: ${{ steps.version.outputs.version }}
          tag_name: ${{ github.run_number }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - run:  cd book_show
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.19.0
      - run: flutter --version
      - name: Install dependencies
        run: cd book_show
      - run: ls
      - run: dart pub get
        working-directory: book_show
      # - name: Install dependencies
      # - run: dart pub get
      - name: Create Env File
        run: | 
            cd book_show
            touch .env
            echo API_KEY = ${{ secrets.API_KEY }} >> .env
            cat .env
      - name: Test
        run: flutter test
        working-directory: book_show
      - name: build artifactry
        run: flutter build apk --release
        working-directory: book_show
      - name: Locate artifactory
        run: | 
            cd book_show/build/app/outputs/apk/release
            ls
      - name: upload artifact
        uses: actions/upload-artifact@v4
        with: 
          name: Release build
          path: book_show/build/app/outputs/apk/release/app-release.apk
      - name: download artifact
        uses: actions/download-artifact@v4
        with:
          name: Release build
      - run: ls $GITHUB_WORKSPACE
      - name: upload apk
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: $GITHUB_WORKSPACE/Release build.zip
          asset_name: release-${{github.run_number}}
          asset_content_type: application/zip
