name: Show Time App

on:
  push:
    branches: [ "workflow" ]
  pull_request:
    branches: [ "workflow" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - run:  cd book_show
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.19.0
      - run: flutter --version
      - name: Install dependencies
      - run: dart pub get
        working-directory: book_show
      - run: flutter test
        working-directory: book_show
